// <auto-generated />
using System;
using Dental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dental.Infrastructure.Migrations
{
    [DbContext(typeof(DentalDbContext))]
    [Migration("20260810180350_FixVisitAppointmentConstraints")]
    partial class FixVisitAppointmentConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Dental.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualVisitDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("ActualVisitDateTime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PatientId");

                    b.Property<DateTime>("ScheduledVisitDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("ScheduledVisitDateTime");

                    b.Property<byte>("Status")
                        .HasColumnType("TINYINT")
                        .HasColumnName("Status")
                        .HasComment("Pending = 1, Canceled = 2, Completed = 3, Missed = 4");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Appointments_PatientId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Dental.Domain.Entities.DentalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("DentalDescription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DentalDescription");

                    b.Property<string>("DentalName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("DentalName");

                    b.Property<string>("DentalPicturePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("DentalPicturePath");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("DoctorName");

                    b.Property<string>("DoctorPicturePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("DoctorPicturePath");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("DentalInfo", null, t =>
                        {
                            t.HasCheckConstraint("CK_DentalInfo_OnlyOneRecord", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DentalDescription = "طب الفم والأسنان",
                            DentalName = "إبتسامه",
                            DoctorName = "د/ كريم فتوح",
                            PhoneNumber = "01006169816"
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.LabTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("LabName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("LabName");

                    b.Property<DateTime>("TranDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("TranDateTime");

                    b.Property<string>("Treatments")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Treatments");

                    b.HasKey("Id");

                    b.HasIndex("LabName")
                        .HasDatabaseName("IX_LabTransaction_LabName");

                    b.HasIndex("TranDateTime")
                        .HasDatabaseName("IX_LabTransaction_TransactionDateTime");

                    b.ToTable("LabTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_LabTransaction_PaidAmount", "[PaidAmount] >= 0");

                            t.HasCheckConstraint("CK_LabTransaction_TotalAmount", "[TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("ReorderLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReorderLevel");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Materials_Name");

                    b.HasIndex("Quantity")
                        .HasDatabaseName("IX_Materials_Quantity");

                    b.HasIndex("ReorderLevel")
                        .HasDatabaseName("IX_Materials_ReorderLevel");

                    b.ToTable("Materials", null, t =>
                        {
                            t.HasCheckConstraint("CK_Materials_Price", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Materials_Quantity", "[Quantity] >= 0");

                            t.HasCheckConstraint("CK_Materials_ReorderLevel", "[ReorderLevel] >= 0");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Age");

                    b.Property<byte>("Gender")
                        .HasColumnType("TINYINT")
                        .HasColumnName("Gender")
                        .HasComment("Male = 0, Female = 1");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Patients_Name");

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patients_AgeRange", "Age BETWEEN 0 AND 99");

                            t.HasCheckConstraint("CK_Patients_Gender", "Gender IN (0, 1)");

                            t.HasCheckConstraint("CK_Patients_PhoneNumberLength", "length(PhoneNumber) = 11");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PatientId");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Prescriptions_PatientId");

                    b.HasIndex("VisitId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prescriptions_VisitId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("Dental.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<decimal>("Dosage")
                        .HasColumnType("TEXT")
                        .HasColumnName("Dosage");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Instructions");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("MedicineName");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PrescriptionId");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("IX_PrescriptionItems_PrescriptionId");

                    b.HasIndex("PrescriptionId", "MedicineName")
                        .IsUnique()
                        .HasDatabaseName("UX_PrescriptionItems_PrescriptionId_MedicineName");

                    b.ToTable("PrescriptionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrescriptionItems_Dosage", "[Dosage] > 0");

                            t.HasCheckConstraint("CK_PrescriptionItems_Period", "[Period] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Supplier_Name");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Supplier_PhoneNumber")
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Suppliers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Suppliers_PhoneNumberLengthEqualTo11", "length(PhoneNumber) = 11");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Treatments_Name");

                    b.ToTable("Treatments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Treatments_Price", "Price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "حشو عصب",
                            Price = 260.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "حشو ليزر",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "تركيبات",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "خلع",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "زراعه",
                            Price = 730.00m
                        },
                        new
                        {
                            Id = 6,
                            Name = "تقويم",
                            Price = 1530.00m
                        },
                        new
                        {
                            Id = 7,
                            Name = "تنظيف جير",
                            Price = 204.00m
                        },
                        new
                        {
                            Id = 8,
                            Name = "تلميع",
                            Price = 143.00m
                        },
                        new
                        {
                            Id = 9,
                            Name = "تبيض",
                            Price = 138.00m
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AppointmentId");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("DiscountAmount");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PatientId");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("VisitDateTime");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Visits_PatientId");

                    b.HasIndex("VisitDateTime")
                        .HasDatabaseName("IX_Visits_VisitDateTime");

                    b.HasIndex("AppointmentId", "PatientId")
                        .IsUnique();

                    b.ToTable("Visits", null, t =>
                        {
                            t.HasCheckConstraint("CK_Visits_DiscountAmount_NotNegative", "[DiscountAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("PaidAmount");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("PaymentDateTime");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_VisitPayments_VisitId");

                    b.ToTable("VisitPayments", null, t =>
                        {
                            t.HasCheckConstraint("CK_VisitPayments_PaidAmount_GreaterThanZero", "[PaidAmount] > 0");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitRadiograph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_VisitRadiograph_VisitId");

                    b.ToTable("VisitRadiographs", (string)null);
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("Count");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<byte?>("ToothNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ToothNumber");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TreatmentId");

                    b.Property<decimal>("TreatmentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("TreatmentPrice");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId")
                        .HasDatabaseName("IX_VisitTreatments_TreatmentId");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("IX_VisitTreatments_VisitId");

                    b.ToTable("VisitTreatments", null, t =>
                        {
                            t.HasCheckConstraint("CK_VisitTreatments_Count_Positive", "[Count] > 0");

                            t.HasCheckConstraint("CK_VisitTreatments_Price_NonNegative", "[TreatmentPrice] >= 0");

                            t.HasCheckConstraint("CK_VisitTreatments_ToothNumber_Range", "[ToothNumber] IS NULL OR [ToothNumber] BETWEEN 1 AND 32");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental.Domain.Entities.LabTransaction", b =>
                {
                    b.OwnsOne("Dental.Domain.ValueObjects.Money", "PaidAmount", b1 =>
                        {
                            b1.Property<int>("LabTransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("PaidAmount");

                            b1.HasKey("LabTransactionId");

                            b1.ToTable("LabTransactions");

                            b1.WithOwner()
                                .HasForeignKey("LabTransactionId");
                        });

                    b.OwnsOne("Dental.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<int>("LabTransactionId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalAmount");

                            b1.HasKey("LabTransactionId");

                            b1.ToTable("LabTransactions");

                            b1.WithOwner()
                                .HasForeignKey("LabTransactionId");
                        });

                    b.Navigation("PaidAmount")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Dental.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dental.Domain.Entities.Visit", "Visit")
                        .WithOne("Prescription")
                        .HasForeignKey("Dental.Domain.Entities.Prescription", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Dental.Domain.ValueObjects.MedicineFrequency", "MedicineFrequency", b1 =>
                        {
                            b1.Property<int>("PrescriptionItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("Period")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Period");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MedicineFrequency");

                            b1.HasKey("PrescriptionItemId");

                            b1.ToTable("PrescriptionItems");

                            b1.WithOwner()
                                .HasForeignKey("PrescriptionItemId");
                        });

                    b.Navigation("MedicineFrequency")
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Visit", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dental.Domain.Entities.Appointment", "Appointment")
                        .WithOne("Visit")
                        .HasForeignKey("Dental.Domain.Entities.Visit", "AppointmentId", "PatientId")
                        .HasPrincipalKey("Dental.Domain.Entities.Appointment", "Id", "PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitPayment", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Visit", "Visit")
                        .WithMany("VisitPayments")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitRadiograph", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Visit", "Visit")
                        .WithMany("VisitRadiographs")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitTreatment", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Treatment", "Treatment")
                        .WithMany("VisitTreatments")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dental.Domain.Entities.Visit", "Visit")
                        .WithMany("VisitTreatments")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Prescriptions");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Treatment", b =>
                {
                    b.Navigation("VisitTreatments");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Visit", b =>
                {
                    b.Navigation("Prescription");

                    b.Navigation("VisitPayments");

                    b.Navigation("VisitRadiographs");

                    b.Navigation("VisitTreatments");
                });
#pragma warning restore 612, 618
        }
    }
}
