// <auto-generated />
using System;
using Dental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dental.Infrastructure.Migrations
{
    [DbContext(typeof(DentalDbContext))]
    partial class DentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Dental.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualVisitDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("ActualVisitDateTime");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("DATETIME('now', 'localtime')");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PatientId");

                    b.Property<DateTime>("ScheduledVisitDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("ScheduledVisitDateTime");

                    b.Property<byte>("Status")
                        .HasColumnType("TINYINT")
                        .HasColumnName("Status")
                        .HasComment("Pending = 1, Canceled = 2, Completed = 3, Missed = 4");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Appointments_PatientId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("Dental.Domain.Entities.DentalInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("DentalDescription")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("DentalDescription");

                    b.Property<string>("DoctorName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("DoctorName");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("PicturePath")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("PicturePath");

                    b.HasKey("Id");

                    b.ToTable("DentalInfo", null, t =>
                        {
                            t.HasCheckConstraint("CK_DentalInfo_OnlyOneRecord", "[Id] = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DentalDescription = "طب الفم والأسنان",
                            DoctorName = "د/ كريم فتوح",
                            PhoneNumber = "+20100619816"
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<decimal>("BuyingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("BuyingPrice");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Quantity");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReorderLevel");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SupplierId");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Quantity");

                    b.HasIndex("SupplierId");

                    b.ToTable("Materials", null, t =>
                        {
                            t.HasCheckConstraint("CK_Material_BuyingPrice", "[BuyingPrice] >= 0");

                            t.HasCheckConstraint("CK_Material_Quantity", "[Quantity] >= 0");

                            t.HasCheckConstraint("CK_Material_ReorderLevel", "[ReorderLevel] >= 0");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("FirstName");

                    b.Property<byte>("Gender")
                        .HasColumnType("TINYINT")
                        .HasColumnName("Gender")
                        .HasComment("Male = 1, Female = 2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("LastName");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patients_Gender", "Gender IN (1, 2)");

                            t.HasCheckConstraint("CK_Patients_PhoneNumberLengthEqualTo11", "length(PhoneNumber) = 11");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PatientId");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_Prescriptions_PatientId");

                    b.HasIndex("VisitId")
                        .IsUnique()
                        .HasDatabaseName("UX_Prescriptions_VisitId");

                    b.ToTable("Prescriptions", (string)null);
                });

            modelBuilder.Entity("Dental.Domain.Entities.PrescriptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<decimal>("Dosage")
                        .HasColumnType("TEXT")
                        .HasColumnName("Dosage");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Instructions");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("MedicineName");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PrescriptionId");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("IX_PrescriptionItems_PrescriptionId");

                    b.HasIndex("PrescriptionId", "MedicineName")
                        .IsUnique()
                        .HasDatabaseName("UX_PrescriptionItems_PrescriptionId_MedicineName");

                    b.ToTable("PrescriptionItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_PrescriptionItems_Dosage", "[Dosage] > 0");

                            t.HasCheckConstraint("CK_PrescriptionItems_Period", "[Period] BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Address");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Supplier_Name");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Supplier_PhoneNumber")
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.ToTable("Suppliers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Suppliers_PhoneNumberLengthEqualTo11", "length(PhoneNumber) = 11");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Treatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Treatments_Name");

                    b.ToTable("Treatments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Treatments_Price", "Price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "حشو عصب",
                            Price = 260.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "حشو ليزر",
                            Price = 450.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "تركيبات",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "خلع",
                            Price = 120.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "زراعه",
                            Price = 730.00m
                        },
                        new
                        {
                            Id = 6,
                            Name = "تقويم",
                            Price = 1530.00m
                        },
                        new
                        {
                            Id = 7,
                            Name = "تنظيف جير",
                            Price = 204.00m
                        },
                        new
                        {
                            Id = 8,
                            Name = "تلميع",
                            Price = 143.00m
                        },
                        new
                        {
                            Id = 9,
                            Name = "تبيض",
                            Price = 138.00m
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AppointmentId");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("DiscountAmount");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("PaidAmount");

                    b.Property<DateTime>("VisitDateTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("VisitDateTime");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_Visits_AppointmentId")
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("VisitDateTime")
                        .IsUnique()
                        .HasDatabaseName("UX_Visits_VisitDateTime");

                    b.ToTable("Visits", null, t =>
                        {
                            t.HasCheckConstraint("CK_Visits_DiscountAmount_NotNegative", "[DiscountAmount] >= 0");

                            t.HasCheckConstraint("CK_Visits_PaidAmount_NotNegative", "[PaidAmount] >= 0");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitTreatment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    SqlitePropertyBuilderExtensions.UseAutoincrement(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Notes");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Price");

                    b.Property<byte>("ToothNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ToothNumber");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TreatmentId");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.HasIndex("VisitId");

                    b.HasIndex("ToothNumber", "VisitId", "TreatmentId")
                        .IsUnique()
                        .HasDatabaseName("UX_VisitTreatments_ToothNumber_VisitId_TreatmentId");

                    b.ToTable("VisitTreatments", null, t =>
                        {
                            t.HasCheckConstraint("CK_VisitTreatments_Price_NonNegative", "[Price] >= 0");

                            t.HasCheckConstraint("CK_VisitTreatments_ToothNumber_Range", "[ToothNumber] >= 1 AND [ToothNumber] <= 32");
                        });
                });

            modelBuilder.Entity("Dental.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Material", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Materials")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dental.Domain.Entities.Visit", "Visit")
                        .WithOne("Prescription")
                        .HasForeignKey("Dental.Domain.Entities.Prescription", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.PrescriptionItem", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Prescription", "Prescription")
                        .WithMany("Items")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Dental.Domain.ValueObjects.MedicineFrequency", "MedicineFrequency", b1 =>
                        {
                            b1.Property<int>("PrescriptionItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("Period")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Period");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MedicineFrequency");

                            b1.HasKey("PrescriptionItemId");

                            b1.ToTable("PrescriptionItems");

                            b1.WithOwner()
                                .HasForeignKey("PrescriptionItemId");
                        });

                    b.Navigation("MedicineFrequency")
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Visit", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Appointment", "Appointment")
                        .WithOne("Visit")
                        .HasForeignKey("Dental.Domain.Entities.Visit", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Dental.Domain.Entities.VisitTreatment", b =>
                {
                    b.HasOne("Dental.Domain.Entities.Treatment", "Treatment")
                        .WithMany("VisitTreatments")
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dental.Domain.Entities.Visit", "Visit")
                        .WithMany("VisitTreatments")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Treatment");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Visit");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Prescription", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Treatment", b =>
                {
                    b.Navigation("VisitTreatments");
                });

            modelBuilder.Entity("Dental.Domain.Entities.Visit", b =>
                {
                    b.Navigation("Prescription");

                    b.Navigation("VisitTreatments");
                });
#pragma warning restore 612, 618
        }
    }
}
